"""Build deterministic demo MP4s from the optional CC0 demo packs (no third-party video is downloaded).

Each scene is a slow zoom over one CC0 stock photo with a CC0 FSD50K clip as its soundtrack, so the
correct content of every interval is known. Requires both demo packs and FFmpeg.

Outputs in data/demo/videos/: scenes.mp4 (4 x 10 s, H.264 + AAC), scenes-silent.mp4 (same video, no audio),
and mediaindex-provenance.json describing each scene interval and its sources.

Usage: uv run python scripts/make_demo_video.py
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
IMG = REPO / "data" / "demo" / "stockimages-cc0"
AUD = REPO / "data" / "demo" / "fsd50k-cc0"
OUT = REPO / "data" / "demo" / "videos"
SCENE_S = 10
SCENES = [  # (image, sound, label for humans only)
    ("stock-02000.jpg", "fsd-150978.flac", "train / railway"),
    ("stock-01642.jpg", "fsd-144028.flac", "dog / barking"),
    ("stock-01683.jpg", "fsd-141471.flac", "insect, meadow / crickets"),
    ("stock-00163.jpg", "fsd-151359.flac", "city at night / traffic"),
]


def run(cmd):
    subprocess.run(cmd, check=True)


def main() -> int:
    ff = shutil.which("ffmpeg")
    if not ff:
        raise SystemExit("ffmpeg is required")
    OUT.mkdir(parents=True, exist_ok=True)
    tmp = OUT / ".build"
    tmp.mkdir(exist_ok=True)
    parts = []
    for i, (img, snd, _) in enumerate(SCENES):
        part = tmp / f"scene{i}.mp4"
        frames = SCENE_S * 25
        run([ff, "-v", "error", "-y", "-loop", "1", "-i", str(IMG / img), "-i", str(AUD / snd),
             "-filter_complex",
             f"[0:v]scale=1280:720:force_original_aspect_ratio=increase,crop=1280:720,"
             f"zoompan=z='min(1+0.0008*on,1.2)':d={frames}:s=1280x720:fps=25,format=yuv420p[v];"
             f"[1:a]aformat=sample_rates=44100:channel_layouts=stereo,apad=whole_dur={SCENE_S}[a]",
             "-map", "[v]", "-map", "[a]", "-t", str(SCENE_S), "-c:v", "libx264", "-preset", "veryfast",
             "-crf", "23", "-g", "25", "-c:a", "aac", "-b:a", "128k", "-bitexact", str(part)])
        parts.append(part)
    lst = tmp / "list.txt"
    lst.write_text("".join(f"file '{p.name}'\n" for p in parts))
    out = OUT / "scenes.mp4"
    run([ff, "-v", "error", "-y", "-f", "concat", "-safe", "0", "-i", str(lst), "-c", "copy",
         "-movflags", "+faststart", str(out)])
    silent = OUT / "scenes-silent.mp4"
    run([ff, "-v", "error", "-y", "-i", str(out), "-an", "-c:v", "copy", "-movflags", "+faststart", str(silent)])
    shutil.rmtree(tmp)
    img_prov = json.loads((IMG / "mediaindex-provenance.json").read_text())["items"]
    aud_prov = json.loads((AUD / "mediaindex-provenance.json").read_text())["items"]
    scenes = [{"start_s": i * SCENE_S, "end_s": (i + 1) * SCENE_S, "label": lab,
               "image": {"file": img, "source": img_prov[img]["source"], "license": img_prov[img]["license_declared"]},
               "sound": {"file": snd, "source": aud_prov[snd]["source"], "license": aud_prov[snd]["license_declared"],
                         "uploader": aud_prov[snd]["uploader"]}}
              for i, (img, snd, lab) in enumerate(SCENES)]
    items = {}
    for f in (out, silent):
        items[f.name] = {
            "file": f.name, "sha256": hashlib.sha256(f.read_bytes()).hexdigest(),
            "license_declared": "Derived from CC0-declared sources (see scenes); generated locally by scripts/make_demo_video.py",
            "source": "generated by scripts/make_demo_video.py from the optional demo packs",
            "scenes": scenes, "has_audio": f is out,
            "tags": "; ".join(f"{s['start_s']}-{s['end_s']}s {s['label']}" for s in scenes),
        }
    (OUT / "mediaindex-provenance.json").write_text(json.dumps({
        "dataset": "MediaIndex generated demo video", "revision": None,
        "license_declared": "derived from CC0-declared images and clips",
        "note": "Each scene's original image/sound and its publisher-declared license are listed; no rights audit.",
        "items": items}, indent=1))
    for f in (out, silent):
        print(f, f.stat().st_size, items[f.name]["sha256"][:16])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
